import type { Metadata } from "next";
import { PageIntro } from "@/components/page-intro";

export const metadata: Metadata = { title: "Contact" };

const questions = [
  { question: "Our QA organization has worked well for years. Do we really need to change it because of AI?", paragraphs: ["Maybe not everything needs to change. But everything deserves to be questioned.", "The QA practices that brought your organization this far still have value. Your people have built years of product knowledge, engineering experience and business understanding. AI should not make that irrelevant.", "The opportunity is to understand what should remain, what can evolve and where AI can remove effort that no longer needs to be human."], closing: "Transformation should protect what works while preparing the organization for what comes next." },
  { question: "Can we reduce QA costs without reducing our people?", paragraphs: ["This is one of the most important questions leaders are asking. Cost optimization does not always have to begin with headcount.", "There may be significant cost hidden in long regression cycles, automation maintenance, repetitive analysis, duplicated tools, inefficient processes, test-data preparation, rework and delayed releases.", "We look for those opportunities first—using productivity, AI, automation and operating-model improvements to enable existing people to contribute at a higher level."], closing: "Optimize the work before optimizing the workforce." },
  { question: "We have invested heavily in automation. Why are we still not seeing the efficiency we expected?", paragraphs: ["This is more common than many organizations realize. Over time, automation itself can become something that requires significant people, maintenance, infrastructure and attention.", "The question is no longer simply, “How much have we automated?” It is, “How much business value is our automation actually creating?”", "We help organizations look beyond automation coverage and understand maintainability, execution efficiency, release impact, risk coverage and the true cost of maintaining the automation ecosystem."], closing: "Measure automation by the value it creates—not only by how much it covers." },
  { question: "Everyone is talking about AI in testing. Where should we actually use it?", paragraphs: ["You do not need AI everywhere. You need it where it matters.", "Buying an AI tool or giving engineers access to an AI assistant does not automatically create an AI-enabled QA organization.", "AI can potentially help with test design, automation development, failure analysis, test data, regression optimization, quality intelligence and risk identification. But the right starting point is different for every organization."], closing: "Start with the problem. Then decide whether AI is the right answer." },
  { question: "What happens to our QA engineers as AI becomes more capable?", paragraphs: ["Behind every AI transformation strategy is a very human question: “What happens to our people?”", "Experienced QA professionals carry something AI cannot simply recreate overnight—product knowledge, customer understanding, business context, engineering judgment and years of organizational experience.", "The opportunity is to combine that knowledge with AI, moving people away from repetitive execution and toward quality engineering, architecture, risk intelligence, AI-assisted testing and engineering decision-making."], closing: "AI should not only make QA faster. It should make QA professionals more capable." },
  { question: "How do we know if our QA organization is actually expensive?", paragraphs: ["The visible QA budget tells only part of the story.", "The real cost of quality can also exist in regression time, automation maintenance, production defects, rework, release delays, environment issues, manual investigation and duplicated tooling.", "Sometimes the biggest QA cost is not sitting in the QA budget at all. We help organizations make these hidden costs visible and identify where change can create measurable business value."], closing: "Make the full cost of quality visible before deciding where to change." },
  { question: "Do we need to replace our existing tools and automation frameworks to become AI-ready?", paragraphs: ["Transformation does not mean throwing away everything you have already built.", "Your organization may have spent years building frameworks, processes, knowledge and engineering capability. We start by understanding that investment.", "Keep what works. Modernize what can improve. Integrate AI where it creates value. Replace something only when there is a clear business reason to do so."], closing: "Good transformation builds on your strengths rather than starting from zero." },
  { question: "This sounds like a large transformation. Where do we even begin?", paragraphs: ["You do not need to begin with transformation. Begin with understanding.", "Understand where your QA effort goes today, what is slowing releases, where automation is helping—and where it has become expensive—what your people spend time on and where AI could genuinely make a difference.", "Then decide what should stay, what should change and what should come next. That is why our first conversation does not have to start with a solution."], closing: "Bring us your QA challenge. Let’s start there." },
] as const;

export default function ContactPage() {
  return <PageIntro eyebrow="Contact" title="Bring us your QA challenge. Let’s start there." intro="You do not need a completed AI strategy, a shortlist of tools or all the answers. Start with the question your engineering organization is trying to solve.">
    <section className="leader-questions" aria-labelledby="leader-questions-title">
      <div className="section-heading"><span className="eyebrow">A practical starting point</span><h2 id="leader-questions-title">Questions engineering leaders are asking</h2><p>Explore the questions we regularly help quality and engineering leaders work through.</p></div>
      <div className="question-list">{questions.map(({ question, paragraphs, closing }, index) => <details key={question}><summary><span>{String(index + 1).padStart(2, "0")}</span><strong>{question}</strong><i aria-hidden="true">+</i></summary><div className="question-answer">{paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<strong>{closing}</strong></div></details>)}</div>
    </section>
    <div className="contact-panel"><div><span className="eyebrow">Still have questions?</span><h2>Let’s rethink what your QA organization could become.</h2><p>Quality strategy, organizational friction, automation modernization, AI adoption, release confidence or an independent transformation assessment—we can begin wherever the challenge is most pressing.</p><div className="contact-details"><a href="tel:+919980546951">+91 99805 46951</a><a href="mailto:hello@qaaiworks.com">hello@qaaiworks.com</a></div></div><div className="contact-actions"><a className="button" href="tel:+919980546951">Call Us ↗</a><a className="text-link" href="mailto:hello@qaaiworks.com">Email Us →</a></div></div>
  </PageIntro>;
}
